genres = [
    # Fiction Genres
    "Adventure",
    "Action",
    "Fantasy",
    "Science Fiction",
    "Mystery",
    "Horror",
    "Thriller",
    "Suspense",
    "Romance",
    "Historical Fiction",
    "Literary Fiction",
    "Young Adult (YA)",
    "Children's Fiction",
    "Urban Fantasy",
    "Paranormal",
    "Dystopian",
    "Magical Realism",
    "Superhero",
    "Cyberpunk",
    "Steampunk",
    "Gothic",
    "Crime",
    "Detective",
    "Western",
    "War",
    "Espionage",
    "Political Fiction",
    "Speculative Fiction",
    "Humor",
    "Satire",
    "Fairy Tale",
    "Mythology",
    # Non-Fiction Genres
    "Biography",
    "Autobiography",
    "Memoir",
    "Self-Help",
    "Personal Development",
    "Health & Wellness",
    "Psychology",
    "True Crime",
    "History",
    "Science & Technology",
    "Philosophy",
    "Religion & Spirituality",
    "Political Science",
    "Business & Economics",
    "Education",
    "Travel",
    "Food & Cooking",
    "Art & Photography",
    "Craft & Hobbies",
    "Music",
    "Film & Television",
    "Theater & Drama",
    "Sports",
    "Nature & Environment",
    "Gardening & Horticulture",
    "Pets & Animal Care",
    "Parenting & Family",
    "Social Sciences",
    "Law",
    "Reference",
    "Essays",
    "Journalism",
    # Hybrid or Crossover Genres
    "Historical Romance",
    "Science Fiction Fantasy",
    "Paranormal Romance",
    "Biographical Fiction",
    "Literary Journalism",
    "Docufiction",
]
